import 'dotenv/config';
import { DeepPartial, FindOptionsWhere, Repository } from 'typeorm';
import { Department } from '../../departments/entities/department.entity';
import { Group } from '../../groups/entities/group.entity';
import { Brand } from '../../brands/entities/brand.entity';
import dataSource from '../data-source';

interface LookupRow {
  code: string;
  name: string;
}

interface LookupEntity {
  code: string;
  name: string;
}

// Source data taken from the DEPARTAMENTOS sheet of the SICAF export.
const DEPARTMENTS: LookupRow[] = [
  { code: '00', name: 'VARIOS' },
  { code: '01', name: 'CHEVROLET' },
  { code: '02', name: 'DAIHATSU' },
  { code: '03', name: 'MITSUBISHI' },
  { code: '04', name: 'NISSAN' },
  { code: '05', name: 'SUZUKI' },
  { code: '06', name: 'TOYOTA' },
  { code: '07', name: 'LAND ROVER' },
  { code: '08', name: 'MAZDA' },
  { code: '09', name: 'COMPRAS PLAZA' },
  { code: '10', name: 'RENAULT' },
  { code: '11', name: 'CHINO' },
  { code: '12', name: 'HYUNDAI' },
  { code: '13', name: 'CHANA' },
  { code: '20', name: 'DAEWOO' },
];

// Source data taken from the GRUPOS sheet of the SICAF export.
const GROUPS: LookupRow[] = [
  { code: '000', name: 'MOTOR3' },
  { code: '001', name: 'MOTOR' },
  { code: '002', name: 'ELECTRICOS' },
  { code: '003', name: 'SUSPENSION Y DIREC2' },
  { code: '004', name: 'CARDAN' },
  { code: '005', name: 'TRANSMISION' },
  { code: '006', name: 'ACCESORIOS Y VARIOS' },
  { code: '007', name: 'LUBRICANTES Y PEGANT' },
  { code: '008', name: 'SUSPENSION Y DIREC' },
  { code: '009', name: 'MOTOR2' },
  { code: '010', name: 'CAJA' },
  { code: '011', name: 'COMPRAS PLAZA' },
  { code: '012', name: 'MOTOR4' },
  { code: '013', name: 'MOTOR5' },
  { code: '014', name: 'CAJA 2' },
  { code: '015', name: 'SUSPENSION Y DIREC4' },
  { code: '016', name: 'MOTOR6' },
  { code: '017', name: 'SUSPENSION Y DIREC3' },
  { code: '018', name: 'TRANSMISION1' },
  { code: '019', name: 'SUSPENSION Y DIREC5' },
  { code: '020', name: 'MOTOR7' },
  { code: '021', name: 'SUSPENSION Y DIREC6' },
  { code: '022', name: 'SUSPENSION Y DIREC7' },
  { code: '023', name: 'MOTOR8' },
];

// Source data taken from the MARCAS sheet of the SICAF export.
const BRANDS: LookupRow[] = [
  { code: '252', name: '3B ARG' },
  { code: '226', name: '555 TW' },
  { code: '0128', name: '555-JP' },
  { code: '0207', name: 'A&G-NAL' },
  { code: '0194', name: 'ACDELCO N' },
  { code: '255', name: 'ADS TW' },
  { code: '0143', name: 'AGGONCAR-N' },
  { code: '0088', name: 'AIG-NAL' },
  { code: '0028', name: 'AIRTEX-USA' },
  { code: '0127', name: 'AISIN-JP' },
  { code: '0076', name: 'ALEMAN' },
  { code: '0213', name: 'ALTAMAX-NAL' },
  { code: '0011', name: 'AMERICANO' },
  { code: '0123', name: 'AMERICANRUBER-N' },
  { code: '0033', name: 'ARGENTINA' },
  { code: '222', name: 'ARISTIC TW' },
  { code: '0042', name: 'ASCO-JP' },
  { code: '0077', name: 'ATE-ALEMAN' },
  { code: '0044', name: 'AUBOS-K' },
  { code: '290', name: 'AUTORIKEN' },
  { code: '0117', name: 'AUTOTEC-TW' },
  { code: '0054', name: 'AVM-BRAZIL' },
  { code: '0160', name: 'AZ-TW' },
  { code: '0068', name: 'BBB-ARG' },
  { code: '0118', name: 'BENBRAND-JP' },
  { code: '0103', name: 'BGF-TW' },
  { code: '0154', name: 'BM-INGL' },
  { code: '233', name: 'BORG-WARBER' },
  { code: '0178', name: 'BOS-ALEMANA' },
  { code: '276', name: 'BOSCH' },
  { code: '232', name: 'BRAZIL' },
  { code: '0167', name: 'BRONCE-N' },
  { code: '0080', name: 'BTK-JP' },
  { code: '0185', name: 'BULL USA' },
  { code: '245', name: 'BW JAPON' },
  { code: '0215', name: 'BWB-JAP' },
  { code: '0170', name: 'CENTEC-TW' },
  { code: '0091', name: 'CENTURI-JP' },
  { code: '0074', name: 'CGP-TW' },
  { code: '220', name: 'CIC-USA' },
  { code: '0202', name: 'CLAYFLEX-ESPAÑA' },
  { code: '0169', name: 'CMB-TW' },
  { code: '0022', name: 'CNC-K' },
  { code: '0210', name: 'COMPRAS PLAZA' },
  { code: '273', name: 'CONTINENTAL' },
  { code: '249', name: 'CONTITECH-AMERI' },
  { code: '282', name: 'CRC' },
  { code: '288', name: 'CTR' },
  { code: '0155', name: 'CWB-K' },
  { code: '0085', name: 'DAEWHA-K' },
  { code: '0061', name: 'DAICO-ARG' },
  { code: '0001', name: 'DAIDO-JP' },
  { code: '0060', name: 'DAIKIN-JP' },
  { code: '254', name: 'DAYCO USA' },
  { code: '248', name: 'DAYO TW' },
  { code: '224', name: 'DELPHI ORIG.' },
  { code: '0125', name: 'DENSO-JP' },
  { code: '239', name: 'DFL NAL' },
  { code: '256', name: 'DIING TW' },
  { code: '0066', name: 'DOKURO-JP' },
  { code: '238', name: 'DONGIL K' },
  { code: '0092', name: 'DREIK-JP' },
  { code: '243', name: 'DRF-NAL' },
  { code: '277', name: 'DS BRAZIL' },
  { code: '284', name: 'ECOM' },
  { code: '251', name: 'EIK´S TW' },
  { code: '0108', name: 'EK-JP' },
  { code: '246', name: 'EKOLINE NAL' },
  { code: '0100', name: 'EMPACAR-NAL' },
  { code: '0162', name: 'ENGINE M-TW' },
  { code: '0032', name: 'EP-USA' },
  { code: '0037', name: 'ERISTIC-TW' },
  { code: '0164', name: 'EXTRA-N' },
  { code: '0112', name: 'FACET-USA' },
  { code: '0153', name: 'FALLONE-ARG.' },
  { code: '0072', name: 'FIC-TRW-JP' },
  { code: '0029', name: 'FRACO-NAL' },
  { code: '281', name: 'FRANING FILTERS' },
  { code: '0114', name: 'FV-TW' },
  { code: '0048', name: 'GABRIEL-NAL' },
  { code: '0071', name: 'GAMAX-NAL' },
  { code: '275', name: 'GAP' },
  { code: '217', name: 'GATES-USA' },
  { code: '176', name: 'GAUSS' },
  { code: '0206', name: 'GEN-JAPON' },
  { code: '247', name: 'GM ORIG.' },
  { code: '0043', name: 'GMB-JP' },
  { code: '0200', name: 'GMB-KOREA' },
  { code: '0204', name: 'GMB-TAILANDIA' },
  { code: '0116', name: 'GMB-TW' },
  { code: '0137', name: 'GMD-TW' },
  { code: '237', name: 'GM-TW' },
  { code: '0111', name: 'HASAKI-JP' },
  { code: '0014', name: 'HASTING-USA' },
  { code: '0084', name: 'HC-NAL' },
  { code: '268', name: 'HELLIN MOTORS' },
  { code: '0209', name: 'HERKO-KOREA' },
  { code: '0176', name: 'HERLUX-AMERIC' },
  { code: '0035', name: 'HIBARI-JP' },
  { code: '0184', name: 'HIBASHI TW' },
  { code: '0129', name: 'HTK-JP' },
  { code: '0148', name: 'HWANGYU-TW' },
  { code: '0039', name: 'ICHIBAN-JP' },
  { code: '272', name: 'IGO' },
  { code: '0165', name: 'IM-TW' },
  { code: '175', name: 'INCOLBEST' },
  { code: '0212', name: 'INCOLCA-NAL' },
  { code: '0198', name: 'INR-NAL' },
  { code: '0146', name: 'INTERNATIONAL-N' },
  { code: '0279', name: 'ISUZU' },
  { code: '218', name: 'ITE TW' },
  { code: '228', name: 'JAFERPA NAL' },
  { code: '0006', name: 'JAPAN' },
  { code: '0097', name: 'JCC-TW' },
  { code: '0150', name: 'JHN-TW' },
  { code: '236', name: 'JMB KOREA' },
  { code: '0115', name: 'JOINFUGI-JP' },
  { code: '278', name: 'JOMO KOREA' },
  { code: '221', name: 'JOZAM-TW' },
  { code: '0147', name: 'JT-TW' },
  { code: '0199', name: 'KAIT-KOREA' },
  { code: '0142', name: 'KARSONS-INGL' },
  { code: '0024', name: 'KASUMA-K' },
  { code: '0136', name: 'KCM-JP' },
  { code: '0109', name: 'KEISTER-JP' },
  { code: '258', name: 'KENICHI NAL' },
  { code: '225', name: 'KGK JAPON' },
  { code: '0019', name: 'KIC-JP' },
  { code: '241', name: 'KML KOREA' },
  { code: '260', name: 'KOK J' },
  { code: '0005', name: 'KOREA' },
  { code: '0038', name: 'KOYO-JP' },
  { code: '0152', name: 'KOYUH-K' },
  { code: '0055', name: 'KP-TW' },
  { code: '0187', name: 'KTC GROUP-K' },
  { code: '0141', name: 'KYB JP' },
  { code: '0027', name: 'KYOSAN-JP' },
  { code: '0090', name: 'LAGZ-NAL' },
  { code: '0157', name: 'LION-TW' },
  { code: '0049', name: 'LOCTITE-NAL' },
  { code: '0151', name: 'LPR-ITAL' },
  { code: '0104', name: 'LUCAS-JP' },
  { code: '0266', name: 'LUK' },
  { code: '0130', name: 'LYO-TW' },
  { code: '0056', name: 'MAG-NAL' },
  { code: '253', name: 'MAHLE BRAZIL' },
  { code: '250', name: 'MAR TW' },
  { code: '0101', name: 'MASTER-JP' },
  { code: '0216', name: 'MATSUDA-J' },
  { code: '0196', name: 'MCILROY-USA' },
  { code: '0082', name: 'METAL LEVE-BRAZ' },
  { code: '261', name: 'MITSUBISH' },
  { code: '280', name: 'MITSUBOSHI' },
  { code: '0119', name: 'MITSUMARU-TW' },
  { code: '0211', name: 'MOBIS-ORIGINAL' },
  { code: '286', name: 'MONROE USA' },
  { code: '0203', name: 'MOTORCRAF-MEXIC' },
  { code: '0133', name: 'MRK-JP' },
  { code: '0023', name: 'MTW' },
  { code: '0070', name: 'MUSASHI-JP' },
  { code: '0205', name: 'MVM-NAL' },
  { code: '0102', name: 'NACHI-JP' },
  { code: '0012', name: 'NACIO-NAL' },
  { code: '0126', name: 'NAKAMOTO-TW' },
  { code: '240', name: 'NANCO TW' },
  { code: '0078', name: 'NAPCO-JP' },
  { code: '0052', name: 'NARVA-GERMANI' },
  { code: '0201', name: 'NATIONAL-AMERIC' },
  { code: '0036', name: 'NAVCAR-NAL' },
  { code: '0000', name: 'NDC-JP' },
  { code: '219', name: 'NECCO K' },
  { code: '0219', name: 'NEW PROTECH K' },
  { code: '0034', name: 'NEWERA-JP' },
  { code: '0173', name: 'NGK-J' },
  { code: '0149', name: 'NINGBO-K' },
  { code: '0113', name: 'NIPONDENSO-JP' },
  { code: '0045', name: 'NKK-JP' },
  { code: '0031', name: 'NOK-JP' },
  { code: '0134', name: 'NOK-SINGAPUR' },
  { code: '0131', name: 'NOVEX-NAL' },
  { code: '0053', name: 'NOVOA-K' },
  { code: '0188', name: 'NPC-J' },
  { code: '0050', name: 'NPC-K' },
  { code: '244', name: 'NPK K' },
  { code: '0009', name: 'NPR-JP' },
  { code: '0051', name: 'NPW-JP' },
  { code: '0067', name: 'NSK-JP' },
  { code: '227', name: 'NSO JAPON' },
  { code: '223', name: 'NTK JAPON' },
  { code: '0013', name: 'NTN-JP' },
  { code: '0135', name: 'OBC-JP' },
  { code: '291', name: 'OKAP' },
  { code: '0004', name: 'ORIGINAL' },
  { code: '0214', name: 'OSAKA NUT-J' },
  { code: '0003', name: 'OSK-JP' },
  { code: '0158', name: 'PARAUT-J' },
  { code: '271', name: 'PARMO' },
  { code: '0218', name: 'PARTCRAFT-USA' },
  { code: '0174', name: 'PEACE TW' },
  { code: '287', name: 'PEGAUCHO' },
  { code: '0094', name: 'PERFECT-JP' },
  { code: '242', name: 'PEVISA-K' },
  { code: '231', name: 'PMC-K' },
  { code: '0183', name: 'POWER TW' },
  { code: '0075', name: 'PRECISION-USA' },
  { code: '0168', name: 'PRIME-TW' },
  { code: '0073', name: 'QAP-TW' },
  { code: '0163', name: 'QTY-TW' },
  { code: '283', name: 'RACING NC' },
  { code: '0197', name: 'RBH TW' },
  { code: '0059', name: 'REICK-K' },
  { code: '0017', name: 'RIGHTWAY-TW' },
  { code: '0010', name: 'RIK-JP' },
  { code: '0139', name: 'ROCKY-JP' },
  { code: '0179', name: 'RU-TW' },
  { code: '0064', name: 'SABO-BRAZIL' },
  { code: '0193', name: 'SAFETY-KOREA' },
  { code: '0172', name: 'SAFETY-TW' },
  { code: '0098', name: 'SANKEI-JP' },
  { code: '0166', name: 'SBK-J' },
  { code: '0081', name: 'SCHADEK-BRAZIL' },
  { code: '234', name: 'SCHUTZE ALEMANA' },
  { code: '230', name: 'SD TW' },
  { code: '0122', name: 'SECO-K' },
  { code: '0002', name: 'SEIWA-JP' },
  { code: '0046', name: 'SHIBUMI-K' },
  { code: '0171', name: 'SHIN-ICHI-K' },
  { code: '0057', name: 'SIME-VENEZ' },
  { code: '269', name: 'SIMONIZ' },
  { code: '0124', name: 'SINGAPUR' },
  { code: '0079', name: 'SINTECO-NAL' },
  { code: '0063', name: 'SINTRAMETAL-ARG' },
  { code: '279', name: 'SNR FRANCES' },
  { code: '235', name: 'SOG TW' },
  { code: '0156', name: 'SONYCO-J' },
  { code: '178', name: 'SPARK' },
  { code: '177', name: 'SPARKTECH' },
  { code: '0025', name: 'SPICER-NAL' },
  { code: '0190', name: 'STEEL K' },
  { code: '0062', name: 'SUN-JP' },
  { code: '0106', name: 'SUPER-JP' },
  { code: '0189', name: 'SYC K' },
  { code: '0018', name: 'TAHIO-JP' },
  { code: '0007', name: 'TAIHO-JP' },
  { code: '0015', name: 'TAIWAN' },
  { code: '0083', name: 'TAMA-JP' },
  { code: '0110', name: 'TAMAYO-NAL' },
  { code: '0191', name: 'TARABUSI' },
  { code: '285', name: 'TECH PARTS' },
  { code: '0086', name: 'TEN10-TW' },
  { code: '0121', name: 'TEXACO-NAL' },
  { code: '0181', name: 'TEZUKA-J' },
  { code: '0140', name: 'THAIO-JP' },
  { code: '0182', name: 'THG-TW' },
  { code: '0058', name: 'TH-NAL' },
  { code: '0030', name: 'THO-JP' },
  { code: '0186', name: 'THREE FIVE TW' },
  { code: '0208', name: 'TIMING-TW' },
  { code: '0145', name: 'TIMKEN-USA' },
  { code: '270', name: 'TITAN' },
  { code: '0016', name: 'TKD-JP' },
  { code: '0008', name: 'TNK-NAL' },
  { code: '0161', name: 'TOBA-TW' },
  { code: '229', name: 'TOKEI TW' },
  { code: '0047', name: 'TOKICO-JP' },
  { code: '0096', name: 'TOKO-JP' },
  { code: '274', name: 'TOMITA' },
  { code: '0065', name: 'TORICA-JP' },
  { code: '0040', name: 'TOTO-JP' },
  { code: '0087', name: 'TOTO-KOREA' },
  { code: '0221', name: 'TOYO-J' },
  { code: '0020', name: 'TP-JP' },
  { code: '0099', name: 'TRANSEJES-NAL' },
  { code: '0105', name: 'TRC-JP' },
  { code: '0138', name: 'TRM-JP' },
  { code: '259', name: 'TRU SPARK NAL' },
  { code: '0192', name: 'TSK JAP' },
  { code: '0095', name: 'TZK-JP' },
  { code: '0195', name: 'UFR TW' },
  { code: '0180', name: 'UNIFAR-TW' },
  { code: '257', name: 'UNITED TW' },
  { code: '0021', name: 'VALEO-K' },
  { code: '293', name: 'VARIOS' },
  { code: '0089', name: 'VICTOR-NAL' },
  { code: '0177', name: 'VPH-KOREA' },
  { code: '0069', name: 'WARNER-NAL' },
  { code: '0120', name: 'WILSON-K' },
  { code: '0159', name: 'WTB-TW' },
  { code: '0093', name: 'WYR-TW' },
  { code: '0026', name: 'YEC-JP' },
  { code: '0175', name: 'YK TW' },
  { code: '0220', name: 'YOTO TW' },
  { code: '292', name: 'YPR' },
  { code: '0144', name: 'YSK-K' },
  { code: '289', name: 'ZTR  AUTO PARTS' },
  { code: '0132', name: 'ZUIKO-JP' },
];

async function seedLookup<T extends LookupEntity>(
  repository: Repository<T>,
  rows: LookupRow[],
  label: string,
): Promise<void> {
  let created = 0;
  let skipped = 0;

  for (const row of rows) {
    const existing = await repository.findOne({
      where: { code: row.code } as FindOptionsWhere<T>,
    });

    if (existing) {
      skipped++;
      continue;
    }

    const entity = repository.create({
      code: row.code,
      name: row.name,
    } as DeepPartial<T>);
    await repository.save(entity);
    created++;
  }

  console.log(`${label}: created ${created}, skipped ${skipped} (already existed)`);
}

async function seed(): Promise<void> {
  await dataSource.initialize();

  await seedLookup(dataSource.getRepository(Department), DEPARTMENTS, 'Departments');
  await seedLookup(dataSource.getRepository(Group), GROUPS, 'Groups');
  await seedLookup(dataSource.getRepository(Brand), BRANDS, 'Brands');

  await dataSource.destroy();
}

seed().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
